---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authproxy.fullname" . }}-config
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;

        location /status {
          return 200;
        }

        # -------------------------------------------------
        # GEM
        # -------------------------------------------------
        # Used by Grafana Agent
        location /prometheus {
          set $prom_auth_bearer $http_authorization;

          proxy_hide_header authorization;

          if ($prom_auth_bearer ~ "^Bearer (.+)$" ) { 
            set $prom_auth_bearer "Bearer $http_x_scope_orgid:$1";
          }
          proxy_set_header authorization $prom_auth_bearer;

          proxy_pass {{ .Values.gem.gateway}}/api/v1/push;
        }

        # Used by Grafana when adding a data source
        location ~ /gem/prometheus/(.*)$ {
          set $promPath $1;
          
          set $bearer "Bearer "; 

          proxy_set_header x_id_token "";

          proxy_set_header authorization "Bearer $http_x_scope_orgid:$http_x_id_token";

          proxy_pass {{ .Values.gem.gateway}}/prometheus/$promPath;
        }

        # Used by Grafana when configuring the plugin
        location ~ /gem/(.*)$ {
          set $gemPath $1;
          proxy_pass {{ .Values.gem.gateway}}/$gemPath;
        }
      }
    }
    