image:
  repository: grafana/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.24.2"


serviceAccount:
  create: true
  annotations: {}
  name: ""


service:
  port: 80

config:
  cluster_label_value: ""
  remote_write_url_a: ""
  remote_write_url_b: ""
  tenant_name: ""
  client_id: ""
  client_secret: ""
  oidc_token_url: ""
  agent_config: ""