apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-agent.fullname" . }}-oidc
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  client_secret: {{ .Values.config.client_secret }}

