apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "grafana-agent.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "grafana-agent.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "grafana-agent.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - -config.file=/etc/agent/agent.yaml
        - -enable-features=integrations-next
        - -server.http.address=0.0.0.0:{{ .Values.service.port }}
        command:
        - /bin/agent
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http-metrics
        volumeMounts:
        - name: logs
          mountPath: /var/log
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /var/lib/agent
          name: agent-wal
        - mountPath: /etc/agent
          name: grafana-agent
        - mountPath: {{ .Values.config.client_secret_path }}
          name: client-secret
      serviceAccount: grafana-agent
      volumes:
      - name: logs
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: grafana-agent
        configMap:
          name: grafana-agent
      - name: client-secret
        secret:
          secretName: {{ include "grafana-agent.fullname" . }}-oidc
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: agent-wal
      namespace: default
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi