image:
  repository: grafana/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.24.2"


serviceAccount:
  create: true
  annotations: {}
  name: ""


service:
  port: 80

config:
  agent_config: ""
  client_secret: ""
  client_secret_path: "/var/run/secrets"